#cloud-config
package_update: true
package_upgrade: false
packages:
  - git
  - default-jre
  - python3-pandas
  - python3-matplotlib
runcmd:
  - echo -n `hostname -I`" ">>/etc/hosts
  - cat /etc/hostname>>/etc/hosts
  - ["cd","/tmp"]
  - ["git","clone","https://github.com/cgeroux/cloud-init-spark.git"]
  - ["./cloud-init-spark/setup.py","/usr/local/"]
  - ["rm","-rf","./cloud-init-spark"]
